name: Apply Terraform on Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:
      branches:
        - main

jobs:
  apply:
    name: Build infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR

        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Terraform fmt
          uses: hashicorp/setup-terraform@v2
          id: fmt
          working-directory: ./terraform_weather_data
          run: terraform fmt 

        - name: Terraform Init
          id: init
          working-directory: ./terraform_weather_data
          run: terraform init

        - name: Terraform Validate
          id: validate
          working-directory: ./terraform_weather_data
          run: terraform validate

        - name: Terraform Apply
          id: apply
          working-directory: ./terraform_weather_data
          run: terraform apply -auto-approve